name: "terrafrom-infra"

on:
  push: 
    branches:
       - futurebranch1


jobs:
   terraform:
     name: "Terraform"
     runs-on: ubuntu-latest
     env:
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRETS_ID }}
       AWS_REGION: "us-west-2"

     steps:
        - name:  checkout
          uses:  action/checkout@v2

        - name:  Setup Terraform
          uses: hasicorp/setup-terraform@v1

        - name: Terraform init
          id: init
          run: terraform init

        - name: Terraform plan
          id: plan
          if: github.event_name == 'push'
          run: terraform plan -no-color
